# This is the config file for the instore server

title = 'development instore server config'

[owner]
name = 'Derrick Chie'

[api]
version = '1.0'

[server]
port = 8080

[database]
db = "local"
password = "password"
user = "user"
host = "postgresql"
port = 5432
