# This is the config file for the instore API Server

title = 'Development instore API Server Config'

[owner]
name = 'Derrick Chie'

[api]
version = '1.0'

[server]
port = 5000

[database]
server = ''
ports = 8080

